# Generated by Django 3.2.5 on 2022-01-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='App',
        ),
    ]
