# Generated by Django 3.2.5 on 2022-02-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
