# Generated by Django 3.2.5 on 2022-01-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Users',
        ),
    ]
