# Generated by Django 3.2.5 on 2022-02-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
