# Generated by Django 3.2.5 on 2022-01-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_app_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
