# Generated by Django 3.2.5 on 2022-02-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_report_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Doctor_id',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
