# Generated by Django 3.2.5 on 2022-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
