# Generated by Django 3.2.5 on 2022-02-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
