# Generated by Django 3.2.5 on 2022-02-14 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_doctor_report_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(to='App.Doctor'),
        ),
    ]
