# Generated by Django 3.2.5 on 2022-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20220214_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
