# Generated by Django 3.2.5 on 2022-02-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='analyse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
    ]
