# Generated by Django 3.2 on 2022-03-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20220217_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(0, ''), (1, '男'), (2, '女')], default=0),
        ),
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('observation', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.doctor')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.image')),
            ],
        ),
    ]
