# Generated by Django 3.2 on 2022-03-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20220321_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagereport',
            name='name',
        ),
    ]
