# Generated by Django 3.2 on 2022-03-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_imagereport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagereport',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.image'),
        ),
    ]
